export const CONFIG = {
  KAKAO_LINK: 'NEXT_PUBLIC_API_SHARE_KAKAO_LINK_KEY',
  API_END_POINT: 'NEXT_PUBLIC_API_END_POINT',
  API_CLOUD: 'NEXT_PUBLIC_API_CLOUD',
  CLINT: 'http://localhost:3000',
  KAKAO_APP_KEY: 'NEXT_PUBLIC_KAKAOMAP_APPKEY',
} as const;
